export const SITE={name:"Banaras Dev Deepawali",phone:"+91 81155 33981",tel:"tel:+918115533981",whatsapp:"https://wa.me/918115533981?text=Hello%2C%20I%20want%20to%20book%20a%20Dev%20Deepawali%20boat%20in%20Varanasi.%20Please%20share%20boat%20options%2C%20availability%20and%20pricing.",whatsappRaw:"https://wa.me/918115533981"};
export const boats=[{title:"Shared Motor Boat",tag:"For couples & small groups",items:["Shared Ganga experience","Illuminated ghat views","Ideal for budget travellers"],price:"Price on Request"},{title:"Private Boat",tag:"For families & private groups",items:["Private river experience","Flexible group experience","Photography-friendly views"],price:"Price on Request"}];
export const faqs=["When is Dev Deepawali celebrated in Varanasi?","How can I book a Dev Deepawali boat?","Do you offer shared boats?","Do you offer private boats?","How many people can a boat accommodate?","What time should I reach the boarding point?","Where does the boat depart from?","Can families and children join?","Can I book for a group?","How do I contact you?"];
export const images=[
{src:"https://commons.wikimedia.org/wiki/Special:FilePath/Dev_Deepavali_at_Varanasi_DSC04305_16.jpg?width=1500",alt:"Dev Deepawali lights in Varanasi",credit:"Sumita Roy Dutta / Wikimedia Commons"},
{src:"https://commons.wikimedia.org/wiki/Special:FilePath/Ghats_of_Varanasi_Getting_ready_for_Dev_Deepawali_41.jpg?width=1200",alt:"Varanasi ghats prepared for Dev Deepawali",credit:"Goutam1962 / Wikimedia Commons"},
{src:"https://commons.wikimedia.org/wiki/Special:FilePath/Dev_Deepavali_at_Varanasi_DSC04305_07.jpg?width=1200",alt:"Dev Deepawali celebration in Varanasi",credit:"Sumita Roy Dutta / Wikimedia Commons"},
{src:"https://commons.wikimedia.org/wiki/Special:FilePath/Dev_Deepavali_at_Varanasi_DSC04305_12.jpg?width=1200",alt:"Illuminated ghats during Dev Deepawali",credit:"Sumita Roy Dutta / Wikimedia Commons"},
{src:"https://commons.wikimedia.org/wiki/Special:FilePath/View_of_Kashi_Vishwanath_Temple_from_a_boat_at_night.jpg?width=1200",alt:"Kashi Vishwanath Temple viewed from a boat at night",credit:"Immanuelle / Wikimedia Commons"},
{src:"https://commons.wikimedia.org/wiki/Special:FilePath/Night_lights_and_river_ganga.jpg?width=1200",alt:"Night lights along the Ganga",credit:"Srijitsen28 / Wikimedia Commons"}];
