import React,{useState}from"react";import{createRoot}from"react-dom/client";import{SITE,boats,faqs,images}from"./data";import"./styles.css";
const wa=()=>{window.location.href=SITE.whatsapp};
function App(){const[open,setOpen]=useState(null),[light,setLight]=useState(null),[menu,setMenu]=useState(false);return <><header className="nav"><a className="brand" href="#home"><span className="brand-mark">🪔</span><span><b>Banaras Dev Deepawali</b><small>VARANASI</small></span></a><nav className={menu?"open":""}>{["Home","Boats","Gallery","About","FAQ"].map(x=><a key={x} href={"#"+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}<button className="gold nav-cta" onClick={wa}>◉&nbsp; Book Now</button></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">☰</button></header>
<main>
<section id="home" className="hero"><div className="hero-bg"/><div className="hero-shade"/><div className="hero-content"><span className="eyebrow">—&nbsp; Experience the divine &nbsp;—</span><h1>Dev Deepawali<br/><em>Boat Tour</em></h1><p>Witness the magical sight of thousands of diyas illuminating the ghats of Varanasi — once a year, a spiritual spectacle, best experienced from the river.</p><div className="actions"><button className="whatsapp" onClick={wa}>◉&nbsp; Book via WhatsApp</button><a className="outline" href={SITE.tel}>⌕&nbsp; Call Now</a></div><div className="hero-trust"><span>♧<b>Spectacular<br/>Ghat Views</b></span><span>♨<b>Comfortable<br/>Boats</b></span><span>▣<b>Unforgettable<br/>Moments</b></span></div></div></section>

<section id="boats" className="boats-section"><div className="center"><span className="eyebrow">—&nbsp; Our boats &nbsp;—</span><h2>Choose Your Perfect Experience</h2><p>We offer a range of boats to make your Dev Deepawali experience special,<br className="desktop"/> comfortable and memorable.</p></div><div className="boat-grid">{boats.map((b,i)=><article className="boat" key={b.title}><div className="boat-image"><img src={images[b.image].src} alt={images[b.image].alt}/></div><div className="boat-body"><h3>{b.title}</h3><p>♟&nbsp; {b.capacity}</p><span className="price">Price on Request</span></div></article>)}</div></section>

<section id="gallery" className="gallery-section"><div className="center"><span className="eyebrow">—&nbsp; Gallery &nbsp;—</span><h2>Moments That Stay Forever</h2><p>A glimpse of the divine beauty, glowing ghats and serene boat rides.</p></div><div className="gallery">{images.map((im,i)=><button aria-label={"Open "+im.alt} key={im.src} className={"g g"+i} onClick={()=>setLight(i)}><img loading={i?"lazy":"eager"} src={im.src} alt={im.alt}/></button>)}</div></section>

<section id="about" className="benefits"><div><span className="benefit-icon">♧</span><h3>Spiritual Experience</h3><p>Witness the unique blend of faith, culture and tradition.</p></div><div><span className="benefit-icon">▣</span><h3>Unmatched Views</h3><p>Best views of illuminated ghats from the comfort of your boat.</p></div><div><span className="benefit-icon">♢</span><h3>Safe &amp; Comfortable</h3><p>Well-maintained boats with experienced boatmen.</p></div><div><span className="benefit-icon">☆</span><h3>Limited Time</h3><p>This is a once-a-year event. Don't miss it!</p></div></section>

<section id="faq" className="faq-section"><div className="center"><span className="eyebrow">—&nbsp; FAQ &nbsp;—</span><h2>Frequently Asked Questions</h2></div><div className="faq-grid">{faqs.map((q,i)=><div className="faq-row" key={q}><button onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><b>{open===i?"−":"⌄"}</b></button>{open===i&&<p>Please contact us on WhatsApp for the latest availability and details.</p>}</div>)}</div></section>
</main>
<footer><div><b>Banaras Dev Deepawali</b><span>Dev Deepawali Boat Experience • Varanasi</span></div><a href={SITE.whatsappRaw}>WhatsApp</a><a href={SITE.tel}>{SITE.phone}</a><small>Boat availability, timings and pricing are subject to confirmation.<br/>© 2026 Banaras Dev Deepawali. All rights reserved.</small></footer>
<div className="mobile-bar"><button onClick={wa}>◉&nbsp; Book via WhatsApp</button><a href={SITE.tel}>⌕&nbsp; Call Now</a></div>
{light!==null&&<div className="lightbox" onClick={()=>setLight(null)}><button aria-label="Close gallery">×</button><img src={images[light].src} alt={images[light].alt}/><span>{images[light].credit}</span></div>}</>}
createRoot(document.getElementById("root")).render(<App/>);