import React,{useState}from"react";import{createRoot}from"react-dom/client";import{SITE,boats,faqs,images}from"./data";import"./styles.css";

const wa=()=>{window.location.href=SITE.whatsapp};

function App(){
 const[open,setOpen]=useState(null),[light,setLight]=useState(null),[menu,setMenu]=useState(false);
 return <><header className="nav"><a className="brand" href="#home"><span className="brand-mark">🪔</span><span><b>Banaras Dev Deepawali</b><small>VARANASI</small></span></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">☰</button><nav className={menu?"open":""}>{["Experience","Boats","Gallery","FAQ","Contact"].map(x=><a key={x} href={"#"+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}<button className="gold nav-cta" onClick={wa}>Book Your Boat</button></nav></header>

<main>
<section id="home" className="hero"><div className="hero-bg"/><div className="hero-shade"/><div className="hero-content"><div className="hero-copy"><span className="eyebrow">— Experience the divine —</span><h1>Dev Deepawali<br/><em>Boat Experience</em></h1><p>Witness the magical night of thousands of diyas illuminating the ghats of Varanasi — best experienced from the river.</p><div className="actions"><button className="whatsapp" onClick={wa}>◉&nbsp; Book via WhatsApp</button><a className="outline" href={SITE.tel}>⌕&nbsp; Call Now</a></div><div className="hero-trust"><span>🪔<b>Ghat Views</b></span><span>🚤<b>Boat Options</b></span><span>📸<b>Photo Moments</b></span></div></div></div></section>

<section id="experience" className="section intro"><div className="photo"><img src={images[0].src} alt={images[0].alt}/><span className="photo-badge">🪔 DEV DEEPAWALI 2026</span></div><div><span className="eyebrow">The night of light</span><h2>Where the Ganga glows with a million lights</h2><p>Once a year, the ghats of Varanasi transform into a breathtaking river of light. Thousands of diyas illuminate the steps of the Ganga, temples glow against the night sky and the river reflects the magic of Dev Deepawali.</p><div className="highlights"><span>🪔 Thousands of Diyas</span><span>🌊 Ganga River Experience</span><span>🏛️ Illuminated Ghats</span><span>📸 Incredible Photo Opportunities</span></div></div></section>

<section id="boats" className="section boats-section"><div className="center"><span className="eyebrow">— Our boats —</span><h2>Choose Your Ganga Experience</h2><p>Clear options, simple booking and availability confirmed directly with you.</p></div><div className="cards">{boats.map((b,i)=><article className="boat" key={b.title}><div className="boat-image"><img src={images[i+2].src} alt={images[i+2].alt}/><span>0{i+1}</span></div><div className="boat-body"><h3>{b.title}</h3><p>{b.tag}</p><ul>{b.items.map(x=><li key={x}>✓ {x}</li>)}</ul><div className="boat-footer"><strong>{b.price}</strong><button className="gold" onClick={wa}>Enquire</button></div></div></article>)}</div></section>

<section className="section dark"><div className="center"><span className="eyebrow">— Why book —</span><h2>A night worth experiencing from the river</h2></div><div className="features">{["Prime Ganga Experience","Easy Booking","Limited Availability","Local Festival Experience","Comfort-focused experience","Perfect for Groups"].map((x,i)=><div key={x}><b>0{i+1}</b><h3>{x}</h3><p>{["See the illuminated ghats from the Ganga.","Connect with us through WhatsApp or phone.","Advance booking is recommended for Dev Deepawali.","Experience the celebration from the river.","Boat details are confirmed at booking.","Options are available for couples, families and groups."][i]}</p></div>)}</div></section>

<section className="section experience"><div className="center"><span className="eyebrow">— The experience —</span><h2>Moments that stay forever</h2><p>A glimpse of the divine beauty, glowing ghats and serene boat rides.</p></div><div className="experience-grid">{["🪔 Thousands of Diyas","🏛️ Illuminated Varanasi Ghats","🌊 Ganga Aarti Atmosphere","🛕 Ancient Temples & Heritage","📸 Stunning Night Photography","✨ The Magical Dev Deepawali Night"].map(x=><div key={x}>{x}</div>)}</div></section>

<section id="gallery" className="section gallery-section"><div className="center"><span className="eyebrow">— Gallery —</span><h2>Varanasi after sunset</h2><p>Explore the glow before you book your place on the river.</p></div><div className="gallery">{images.map((im,i)=><button aria-label={"Open "+im.alt} key={im.src} className={"g g"+i} onClick={()=>setLight(i)}><img loading={i?"lazy":"eager"} src={im.src} alt={im.alt}/><span>View</span></button>)}</div></section>

<section className="section booking"><div className="center"><span className="eyebrow">— Three simple steps —</span><h2>How To Book Your Boat</h2></div><div className="steps">{["Choose Your Boat","Contact Us","Confirm Your Booking"].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Select shared or private boat.","WhatsApp or call with your preferred date, group size and boat type.","We will share availability, pricing and booking details."][i]}</p></div>)}</div><div className="booking-cta"><div><span className="eyebrow">Ready for the river?</span><h3>Make this Dev Deepawali unforgettable.</h3></div><button className="whatsapp" onClick={wa}>◉&nbsp; Book on WhatsApp</button><a className="outline" href={SITE.tel}>Call +91 81155 33981</a></div></section>

<section className="section info"><div><span className="eyebrow">— Before you book —</span><h2>Important information</h2></div><ul><li>Advance booking is recommended for Dev Deepawali.</li><li>Boat availability is limited.</li><li>Exact departure point will be confirmed at booking.</li><li>Timing may depend on river conditions and local administration.</li><li>Pricing may vary by boat type, capacity and timing.</li><li>Please arrive before the scheduled departure.</li><li>Follow local boating and safety instructions.</li></ul></section>

<section id="faq" className="section faq"><div className="center"><span className="eyebrow">— Questions —</span><h2>Frequently Asked Questions</h2></div><div className="faq-grid">{faqs.map((q,i)=><div className="faq-row" key={q}><button onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><b>{open===i?"−":"⌄"}</b></button>{open===i&&<p>Please contact us on WhatsApp for the latest availability and details.</p>}</div>)}</div></section>

<section id="contact" className="final"><div><span className="eyebrow">— Make it unforgettable —</span><h2>See Varanasi<br/><em>illuminated from the Ganga.</em></h2><p>Experience one of India's most magical nights from the river.</p><div className="actions"><button className="whatsapp" onClick={wa}>◉&nbsp; Book Your Boat</button><a className="outline" href={SITE.tel}>Call Now</a></div></div></section>
</main>

<footer><div><b>Banaras Dev Deepawali</b><span>Dev Deepawali Boat Experience • Varanasi</span></div><a href={SITE.whatsappRaw}>WhatsApp</a><a href={SITE.tel}>{SITE.phone}</a><small>Boat availability, timings and pricing are subject to confirmation.<br/>© 2026 Banaras Dev Deepawali. All rights reserved.</small></footer>
<div className="mobile-bar"><button onClick={wa}>◉&nbsp; WhatsApp</button><a href={SITE.tel}>⌕&nbsp; Call Now</a></div>
{light!==null&&<div className="lightbox" onClick={()=>setLight(null)}><button aria-label="Close gallery">×</button><img src={images[light].src} alt={images[light].alt}/><span>{images[light].credit}</span></div>}
</>}

createRoot(document.getElementById("root")).render(<App/>);
