import React,{useState}from"react";import{createRoot}from"react-dom/client";import{SITE,boats,faqs,images}from"./data";import"./styles.css";
const wa=()=>{window.location.href=SITE.whatsapp};
function App(){const[open,setOpen]=useState(null),[light,setLight]=useState(null),[menu,setMenu]=useState(false);return <><header className="nav"><a className="brand" href="#home">🪔 <span>Banaras Dev Deepawali</span></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">☰</button><nav className={menu?"open":""}>{["Experience","Boats","Gallery","FAQ","Contact"].map(x=><a key={x} href={"#"+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}<button className="gold" onClick={wa}>Book Your Boat</button></nav></header><main>
<section id="home" className="hero"><div className="hero-bg"/><div className="hero-content"><span className="eyebrow">✨ Dev Deepawali 2026 • Varanasi</span><h1>Experience Dev Deepawali<br/><em>From the Ganga</em></h1><p>Witness Varanasi come alive with thousands of diyas, illuminated ghats and the divine glow of Dev Deepawali — from the heart of the Ganga.</p><div className="actions"><button className="gold" onClick={wa}>🪔 Book Your Boat</button><button className="outline" onClick={wa}>WhatsApp Us</button></div><a className="phone" href={SITE.tel}>+91 81155 33981</a><small>Limited boats available • Advance booking recommended</small></div></section>
<section id="experience" className="section intro"><div className="photo"><img src={images[0].src} alt={images[0].alt}/></div><div><span className="eyebrow">The night of light</span><h2>Where the Ganga glows with a million lights</h2><p>Once a year, the ghats of Varanasi transform into a breathtaking river of light. Thousands of diyas illuminate the steps of the Ganga, temples glow against the night sky and the river reflects the magic of Dev Deepawali.</p><div className="highlights"><span>🪔 Thousands of Diyas</span><span>🌊 Ganga River Experience</span><span>🏛️ Illuminated Ghats</span><span>🙏 Spiritual Atmosphere</span><span>📸 Incredible Photo Opportunities</span></div></div></section>
<section id="boats" className="section"><div className="center"><span className="eyebrow">Choose your experience</span><h2>Choose Your Ganga Experience</h2><p>Simple booking. Clear options. Availability and pricing confirmed directly with you.</p></div><div className="cards">{boats.map((b,i)=><article className="boat" key={b.title}><span className="num">0{i+1}</span><h3>{b.title}</h3><p>{b.tag}</p><ul>{b.items.map(x=><li key={x}>✓ {x}</li>)}</ul><div className="price">{b.price}</div><button className="gold full" onClick={wa}>Enquire on WhatsApp</button></article>)}</div></section>
<section className="section dark"><div className="center"><span className="eyebrow">Why book</span><h2>A night worth experiencing from the river</h2></div><div className="features">{["Prime Ganga Experience","Easy Booking","Limited Availability","Local Festival Experience","Comfort-focused experience","Perfect for Groups"].map((x,i)=><div key={x}><b>0{i+1}</b><h3>{x}</h3><p>{["See the illuminated ghats from the Ganga.","Connect with us through WhatsApp or phone.","Advance booking is recommended for Dev Deepawali.","Experience the celebration from the river.","Boat details are confirmed at booking.","Options are available for couples, families and groups."][i]}</p></div>)}</div></section>
<section className="section"><div className="center"><span className="eyebrow">The experience</span><h2>What you will experience</h2></div><div className="experience-grid">{["🪔 Thousands of Diyas","🏛️ Illuminated Varanasi Ghats","🌊 Ganga Aarti Atmosphere","🛕 Ancient Temples & Heritage","📸 Stunning Night Photography","✨ The Magical Dev Deepawali Night"].map(x=><div key={x}>{x}</div>)}</div></section>
<section id="gallery" className="section"><div className="center"><span className="eyebrow">See the magic</span><h2>Varanasi after sunset</h2></div><div className="gallery">{images.map((im,i)=><button key={im.src} className={"g g"+i} onClick={()=>setLight(i)}><img loading={i?"lazy":"eager"} src={im.src} alt={im.alt}/></button>)}</div></section>
<section className="section booking"><div className="center"><span className="eyebrow">Three simple steps</span><h2>How To Book Your Boat</h2></div><div className="steps">{["Choose Your Boat","Contact Us","Confirm Your Booking"].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Select shared or private boat.","WhatsApp or call with your preferred date, group size and boat type.","We will share availability, pricing and booking details."][i]}</p></div>)}</div><div className="booking-cta"><h3>Ready to see Varanasi from the Ganga?</h3><button className="gold" onClick={wa}>Book on WhatsApp</button><a href={SITE.tel}>Call +91 81155 33981</a></div></section>
<section className="section info"><div><span className="eyebrow">Before you book</span><h2>Important information</h2></div><ul><li>Advance booking is recommended for Dev Deepawali.</li><li>Boat availability is limited.</li><li>Exact departure point will be confirmed at booking.</li><li>Timing may depend on river conditions and local administration.</li><li>Pricing may vary by boat type, capacity and timing.</li><li>Please arrive before the scheduled departure.</li><li>Follow local boating and safety instructions.</li></ul></section>
<section id="faq" className="section faq"><div className="center"><span className="eyebrow">Questions</span><h2>Frequently Asked Questions</h2></div>{faqs.map((q,i)=><div className="faq-row" key={q}><button onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><b>{open===i?"−":"+"}</b></button>{open===i&&<p>Please contact us on WhatsApp for the latest availability and details.</p>}</div>)}</section>
<section id="contact" className="final"><div><span className="eyebrow">Make it unforgettable</span><h2>See Varanasi<br/><em>illuminated from the Ganga.</em></h2><p>Experience one of India's most magical nights from the river.</p><div className="actions"><button className="gold" onClick={wa}>🪔 Book Your Boat</button><a className="outline" href={SITE.tel}>Call Now</a></div></div></section></main><footer><div><b>Banaras Dev Deepawali</b><span>Dev Deepawali Boat Experience • Varanasi</span></div><a href={SITE.whatsappRaw}>WhatsApp</a><a href={SITE.tel}>{SITE.phone}</a><small>Boat availability, timings and pricing are subject to confirmation.<br/>© 2026 Banaras Dev Deepawali. All rights reserved.</small></footer><div className="mobile-bar"><button onClick={wa}>📱 WhatsApp</button><a href={SITE.tel}>📞 Call Now</a></div>{light!==null&&<div className="lightbox" onClick={()=>setLight(null)}><img src={images[light].src} alt={images[light].alt}/><span>{images[light].credit}</span></div>}</>};createRoot(document.getElementById("root")).render(<App/>);
